POST http://localhost:8000/api/admin/register
Content-Type: application/json

{
  "FirstName" : "Omar",
  "LastName" : "Attia",
  "email" : "omar.aa.attia@gmail.com",
  "password" : secret,
  "password_confirm" : secret
}

###
POST http://localhost:8000/api/admin/register
Content-Type: application/json

{
  "FirstName" : "jeff",
  "LastName" : "anderson",
  "email" : "jeff@gmail.com",
  "password" : secret,
  "password_confirm" : secret
}

###
POST http://localhost:8000/api/admin/register
Content-Type: application/json

{
  "FirstName" : "john",
  "LastName" : "abo 3amo",
  "email" : "jeff@gmail.com",
  "password" : secret,
  "password_confirm" : secret
}

###
POST http://localhost:8000/api/admin/register
Content-Type: application/json

{
  "FirstName" : "pangar",
  "LastName" : "pangoora",
  "email" : "pangar@cat.com",
  "password" : secret,
  "password_confirm" : secret
}
