PUT http://localhost:8000/api/admin/user/info
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZXhwIjoxNjU1NTQ2MDgxfQ.kqvbnITYIrCwc4Ul1YqKfF49mn7FxYUStf4suamEpqw

{
  "FirstName" : "John",
  "LastName" : "Johnny",
  "email" : "jj@gmail.com",
  "password" : "secret",
  "password_confirm" : "secret",
  "IsAmbassador" : "true"
}