PUT http://localhost:8000/api/admin/user/password
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZXhwIjoxNjU1NTQ2MDgxfQ.kqvbnITYIrCwc4Ul1YqKfF49mn7FxYUStf4suamEpqw

{
  "password" : "123",
  "password_confirm" : "123"
}